<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_toggle</name>
   <tag></tag>
   <elementGuidId>4f37984e-b270-4071-b511-e6872d8f52f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form//div[@class=&quot;primaryInput&quot;]/div/input/..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//form//div[@class=&quot;primaryInput&quot;]/div/input/..</value>
   </webElementXpaths>
</WebElementEntity>
