<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TitleText</name>
   <tag></tag>
   <elementGuidId>fb9e8f09-651b-41e0-b035-47a25c847621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;virtual-list-container&quot;]//*[@name=&quot;inputForm&quot;]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@class=&quot;virtual-list-container&quot;]//*[@name=&quot;inputForm&quot;]//input</value>
   </webElementXpaths>
</WebElementEntity>
