<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_inputRange</name>
   <tag></tag>
   <elementGuidId>886cc371-7ca8-4ab6-a056-6aa897268d0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;virtual-list-container&quot;]//*[@class=&quot;inputRange&quot;]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@class=&quot;virtual-list-container&quot;]//*[@class=&quot;inputRange&quot;]/input</value>
   </webElementXpaths>
</WebElementEntity>
