<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FontFamily</name>
   <tag></tag>
   <elementGuidId>b875f063-0e2e-4ec5-87c8-30960c6164d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;virtual-list-container&quot;]//*[@class=&quot;primaryInput&quot;]//span/span[last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@class=&quot;virtual-list-container&quot;]//*[@class=&quot;primaryInput&quot;]//span/span[last()]</value>
   </webElementXpaths>
</WebElementEntity>
