<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_paragraph</name>
   <tag></tag>
   <elementGuidId>c15f928b-454f-4077-86c8-cf09e3080571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;virtual-list-container&quot;]//textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@class=&quot;virtual-list-container&quot;]//textarea</value>
   </webElementXpaths>
</WebElementEntity>
