<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_deviation</name>
   <tag></tag>
   <elementGuidId>76e8a131-ca53-4630-aeb6-dbb5e8c08dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;highcharts-series-group&quot;]/following-sibling::*[name()=&quot;rect&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VisualObject/iframe_visual header</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@class=&quot;highcharts-series-group&quot;]/following-sibling::*[name()=&quot;rect&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
