<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_highcharts-title</name>
   <tag></tag>
   <elementGuidId>41d0520f-8196-4db3-916f-c7aa01ffcd6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;visual-sandbox&quot;]//*[name()=&quot;svg&quot;]//*[@class=&quot;highcharts-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@class=&quot;visual-sandbox&quot;]//*[name()=&quot;svg&quot;]//*[@class=&quot;highcharts-title&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
