<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_highcharts-legend-item</name>
   <tag></tag>
   <elementGuidId>9d525467-3535-4555-8a83-e5db0a64069a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;highcharts-legend&quot;]/*[name()=&quot;g&quot;]/*[name()=&quot;g&quot;]//*[name()=&quot;tspan&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@class=&quot;highcharts-legend&quot;]/*[name()=&quot;g&quot;]/*[name()=&quot;g&quot;]//*[name()=&quot;tspan&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
