<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Revert to default</name>
   <tag></tag>
   <elementGuidId>de0fe3a4-8d34-4122-89f8-d14ec8f6efdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>div[title=&quot;Revert to default&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@type = 'button' and @title = 'Revert to default' and (text() = 'Revert to default' or . = 'Revert to default')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;Revert to default&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clearAll trimmedTextWithEllipsis</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'dirtyCard': $ctrl.viewModel.value}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-switch-when</name>
      <type>Main</type>
      <value>revertToDefault</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible-click</name>
      <type>Main</type>
      <value>$ctrl.change()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize</name>
      <type>Main</type>
      <value>Visual_RevertToDefault</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize-tooltip</name>
      <type>Main</type>
      <value>Visual_RevertToDefaultDescription</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Revert to default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Revert to default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-multipleAxesChartBC35C88E1D1A49DFA5A9240AFBB4E3BC-xaxis&quot;)/property-slice-container[1]/div[1]/property-slice[1]/div[@class=&quot;inputField&quot;]/div[@class=&quot;inputFieldContent&quot;]/div[@class=&quot;primaryInput&quot;]/div[@class=&quot;clearAll trimmedTextWithEllipsis&quot;]</value>
   </webElementProperties>
</WebElementEntity>
