<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_visual-sandbox</name>
   <tag></tag>
   <elementGuidId>d28b207b-2500-4646-804f-17e9482dcc1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@class=&quot;visual-sandbox&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//iframe[@class=&quot;visual-sandbox&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
