<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_chart</name>
   <tag></tag>
   <elementGuidId>bb3e2729-5a1f-462b-9c34-de75d784cd91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@title=&quot;MultipleAxesChart&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@title=&quot;MultipleAxesChart&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
