<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_report</name>
   <tag></tag>
   <elementGuidId>8f68ae80-3dce-4e28-9d2a-f8af8c099eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@localize=&quot;ContentList_Reports&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@localize=&quot;ContentList_Reports&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
